USE [master]
GO

/****** Object:  Database [bookish]    Script Date: 26/10/2022 15:45:04 ******/
CREATE DATABASE [bookish]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bookish', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\bookish.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bookish_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\bookish_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bookish].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bookish] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bookish] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bookish] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bookish] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bookish] SET ARITHABORT OFF 
GO

ALTER DATABASE [bookish] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bookish] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bookish] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bookish] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bookish] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bookish] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bookish] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bookish] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bookish] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bookish] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bookish] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bookish] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bookish] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bookish] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bookish] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bookish] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bookish] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bookish] SET RECOVERY FULL 
GO

ALTER DATABASE [bookish] SET  MULTI_USER 
GO

ALTER DATABASE [bookish] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bookish] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bookish] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bookish] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [bookish] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bookish] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [bookish] SET QUERY_STORE = OFF
GO

ALTER DATABASE [bookish] SET  READ_WRITE 
GO

